### ISSUE TITLE
--scope collides with --service-account in step 7

### ISSUE THREAD

**Issue by peter-fe** [sethvargo/vault-kubernetes-workshop#12]
[Step 7](https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html?index=..%2F..cloud#6)

```
gcloud container clusters create vault \
>   --cluster-version 1.13 \
>   --enable-autorepair \
>   --enable-autoupgrade \
>   --enable-ip-alias \
>   --machine-type n1-standard-1 \
>   --node-version 1.13 \
>   --num-nodes 1 \
>   --region us-east1 \
>   --scopes cloud-platform \
>   --service-account "${SERVICE_ACCOUNT}"
ERROR: (gcloud.container.clusters.create) argument --service-account: At most one of --service-account | --no-enable-cloud-endpoints --scopes may be specified.
```

**Comment by sethvargo** [comment]
Hi @peter-fe 

What version of gcloud are you using? Can you paste the output of `gcloud -v`?

```text
$ gcloud -v
Google Cloud SDK 253.0.0
alpha 2019.06.13
beta 2019.06.13
bq 2.0.44
core 2019.06.28
gsutil 4.39
```

I'm on 253.0.0 and I can't reproduce this issue.

**Comment by peter-fe** [comment]
Hi @sethvargo 

Seems you nailed it, my version was from April and there was a change regarding that in May.

```
245.0.0 (2019-05-07)
...

  Kubernetes Engine
      ▪ Modified gcloud container clusters create and gcloud container
        node-pools create to allow simultaneously specifying both --scopes and
        --service-account flags.
```

Not sure why that was changed, because regarding the [documentation ](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--service-account), as soon as an service account is set the scopes are ignored/defaulting to cloud-platform and userinfo.email.

Or do I get this wrong?

Best,
Peter
