### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by SamourM** [sethvargo/vault-kubernetes-workshop#14]
Hi,

"vault secrets enable vk" should be "vault secrets enable kv".

Thanks.

**Comment by sethvargo** [comment]
Hi @SamourM 

Where do you see this typo?

**Comment by den-vasyliev** [comment]
> Hi @SamourM
> 
> Where do you see this typo?

https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html?index=..%2F..cloud#13

**Comment by sethvargo** [comment]
Fixed
