### ISSUE TITLE
Second container which pulls vault image goes in CrashLoopBackOff

### ISSUE THREAD

**Issue by pravargauba** [sethvargo/vault-kubernetes-workshop#15]
@sethvargo 

So there are 2 containers which runs inside one pod, however image of **vault-init** container gets pulled successfully and get the container running, however there seems to be a problem with the **second (vault)** image. I even changed the vault image from (1.0.2) in your master k8s/vault.yaml to 1.2.2.(in my local), however wasn't fruitful. Both of the images tags aren't working(1.0.2, and 1.2.2). Container keeps on restarting. No logs can be seen as such. Please help us out. Thanks in advance.

```
$ kubectl get pods

NAME        READY      STATUS   RESTARTS   AGE
vault-0        1/2            Error             5          3m58s
```

```
$ kubectl describe pod vault-0

Successfully pulled image "registry.hub.docker.com/library/vault:1.2.2"
Created container
Started container
Back-off restarting failed container
```

PS: We are running everything inside Google cloud shell, and have been following everything presented in this link:

https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html?index=..%2F..cloud#0

Attached is the screenshot of error for better understanding:

<img width="1564" alt="Screenshot 2019-09-09 at 2 53 06 PM" src="https://user-images.githubusercontent.com/18290521/64519332-8de4d600-d311-11e9-98ab-2e196e1f878e.png">

**Modified(new) vault.yaml:**

<img width="503" alt="Screenshot 2019-09-09 at 2 57 17 PM" src="https://user-images.githubusercontent.com/18290521/64519648-24b19280-d312-11e9-9b1a-52fb38dfa4d1.png">

**Comment by sethvargo** [comment]
Hi @pravargauba - I ran through the codelab, updated it to the latest versions, and verified it works end-to-end. Please _refresh_ the codelab and restart from the beginning. Thanks!
