### ISSUE TITLE
the kv-sidecar pod remains in CrashLoopBackOff.

### ISSUE THREAD

**Issue by pravargauba** [sethvargo/vault-kubernetes-workshop#16]
Hi @sethvargo @gdwikir

Thanks for the amazing workshop. I am almost done with setting up everything, and everything seemed to be working fine until I came across this error. Not so sure whether anyone else is facing this issue or not.

**Here are the logs** 

```text
$ kubectl logs -l app=kv-sidecar -c vault-authenticator

2019/09/25 07:36:48 failed to get successful response: &http.Response{Status:"500 Internal Server Error", StatusCode:500, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, Header:http.Header{"Cache-Control":[]string{"
no-store"}, "Content-Length":[]string{"52"}, "Content-Type":[]string{"application/json"}, "Date":[]string{"Wed, 25 Sep 2019 07:36:48 GMT"}}, Body:http2.transportResponseBody{cs:(*http2.clientStream)(0xc00009ea00)}
, ContentLength:52, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc0000d6000), TLS:(*tls.ConnectionState)(0xc000082580)}, {"errors":["could no
t load backend configuration"]}
```

Image is attached below:

<img width="616" alt="Screenshot 2019-09-25 at 1 09 36 PM" src="https://user-images.githubusercontent.com/18290521/65579811-19a76500-df96-11e9-8468-24a1c2150a36.png">

I even tried changing the vault-authenticator image version to latest, still the error seems to persist.

<img width="499" alt="Screenshot 2019-09-25 at 1 15 43 PM" src="https://user-images.githubusercontent.com/18290521/65580079-9fc3ab80-df96-11e9-90ed-a8664af7d187.png">

And because of this failed container, consul-template remains in initialising stage(as it is waiting for vault-authenticator to come up.)

**Comment by sethvargo** [comment]
This error corresponds to when there's [no configuration for the Kubernetes auth method](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_login.go#L98). Can you share more about what steps you took and where you got stuck?

**Comment by pravargauba** [comment]
Hey. was able to sort that out, there was some problem with rbac permission, so now stuck to this. It says that the certificate is signed by unknown authority. I am using ca.crt .. That said, I have **configmap** and **secrets** configured properly already. This certificate is self-signed, hence it is showing as invalid. I have configured as shown in this slide.

kubectl get secret vault-tls

<img width="198" alt="Screenshot 2019-09-25 at 9 03 15 PM" src="https://user-images.githubusercontent.com/18290521/65616083-1208b000-dfd8-11e9-81d5-648431e5aa0f.png">

kubectl get configmap vault
<img width="203" alt="Screenshot 2019-09-25 at 9 06 22 PM" src="https://user-images.githubusercontent.com/18290521/65616327-7f1c4580-dfd8-11e9-9c01-b61e459811f1.png">

**https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html?index=..%2F..cloud#8**

**kubectl logs kv-sidecar-5459db6969-228s2 vault-authenticator**

019/09/25 14:08:25 failed to get successful response: &http.Response{Status:"500 Internal Server Error", StatusCode:500, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, {"errors":["Post h
ttps://<K8s_host>/apis/authentication.k8s.io/v1/tokenreviews: x509: **certificate signed by unknown authority"**]}

PS: The stage I'm stuck on, is same.
<img width="616" alt="Screenshot 2019-09-25 at 1 09 36 PM" src="https://user-images.githubusercontent.com/18290521/65616673-171a2f00-dfd9-11e9-9580-bdba12837bd5.png">
