### ISSUE TITLE
ERROR: (gcloud.kms.decrypt) INVALID_ARGUMENT: Decryption failed: verify that 'name' refers to the correct CryptoKey.

### ISSUE THREAD

**Issue by eah-pavo** [sethvargo/vault-kubernetes-workshop#18]
Hello,

I am following the exact steps from the tutorial, 
https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html?index=..%2F..cloud#12

however I keep getting this error 

CommandException: No URLs matched: gs://ztar-hashicorp-vault-dev-vault-storage/root-token.enc
ERROR: (gcloud.kms.decrypt) INVALID_ARGUMENT: Decryption failed: verify that 'name' refers to the correct CryptoKey.

Looked inside the storage and there are two folders core and sys. What am I missing here? 

Thank you

**Comment by sethvargo** [comment]
Did the Vault cluster start successfully? What do the Stackdriver logs say?

**Comment by eah-pavo** [comment]
Sorry to bother Seth. Your work is much appreciated. I nuked the whole deployment and started all over trying to leverage an internal LB. 

Happy New Year and thank you for the great work that you're doing :)
