### ISSUE TITLE
Where can I source code of sethvargo/vault-demo-app?

### ISSUE THREAD

**Issue by hitxiang** [sethvargo/vault-kubernetes-workshop#2]
This tutorial is awesome and helped me a lot.
But I cannot find the golang source code of  sethvargo/vault-demo-app, is it possible to share?

**Comment by sethvargo** [comment]
It's closed source because it's really quite hacky. All it does is read a file and print it out, like this:

```go
func main() {
  contents, err := ioutil.OpenFile(os.Getenv("SECRETS_FILE"))
  if err != nil {
    log.Fatal(err)
  }

  fmt.Fprintf(os.Stdout, "%s", contents)
}
```

**Comment by hitxiang** [comment]
Thank you! @sethvargo
