### ISSUE TITLE
Can we use Role and Rolebindings instead of clusterroles , init container is failing when i use rolebinding instead of clusterrole binding

### ISSUE THREAD

**Issue by syprasha1994** [sethvargo/vault-kubernetes-workshop#20]

**Comment by sethvargo** [comment]
Hi there, sorry, what are you asking? Can you link to specific sections please?

**Comment by syprasha1994** [comment]
Hello Seth , thank you for replying , I have sucessfully created a vault following your scripts , however while creating a service account in my-app cluster to authenticate to vault I created a sercice account with role and role binding in default namespace , then i deployed the static app , but the pods are stuck in crashloop ( the init container is failing) however if i create the same service account with cluster roles binding , it worked ,
There is a requirement for me to create service account that is namespace specific

**Comment by sethvargo** [comment]
Hi @syprasha1994 - this is probably better asked on the Vault mailing list.
