### ISSUE TITLE
How to automate reconfiguration when the CA for the cluster is rotated.  

### ISSUE THREAD

**Issue by tjitrak** [sethvargo/vault-kubernetes-workshop#22]
Hello Seth,

I have some questions that can we automate reconfiguration when the CA for the cluster is rotated? Right now, I have to do manual reconfiguration when you get a new certificate. 

Thank you

**Comment by sethvargo** [comment]
Hi @tjitrak - cluster CA rotation is [not automatic either](https://cloud.google.com/kubernetes-engine/docs/how-to/credential-rotation) - you would need to update the Vault configuration as part of the rotation process.
