### ISSUE TITLE
Is the consul side car really required?

### ISSUE THREAD

**Issue by rajarajanpsj** [sethvargo/vault-kubernetes-workshop#3]
@sethvargo  Just curious to know, if I am a dev heavily using spring boot, I would not need the consul side car fetching the secrets for me right? I would rather have just the init container do the auth flow, fetch the vault token and give the token to spring boot via annotations and that will fetch the required secrets for me. Does it make sense to avoid the consul side car in this case?

**Comment by sethvargo** [comment]
Yea that's fine :smile:.
