### ISSUE TITLE
Reading vault token in sidecar container from disk

### ISSUE THREAD

**Issue by Phylu** [sethvargo/vault-kubernetes-workshop#4]
When using the official consul-template image `hashicorp/consul-template:alpine`, it will not load the vault token from /home/vault/.vault-token. Instead it expects the token to be present in the `VAULT_TOKEN` environment variable.

Is there any way in your setup to use it with the official conul-template image?

**Comment by sethvargo** [comment]
No - you have to use my fork or ask HashiCorp to push a new version of CT to the registry. Sorry.

**Comment by Phylu** [comment]
Thanks. I will probably do both.
