### ISSUE TITLE
How to renew the vault token

### ISSUE THREAD

**Issue by ghifariram** [sethvargo/vault-kubernetes-workshop#7]
Just curious, the `my-app-role` only has TTL of 15m (https://github.com/sethvargo/vault-kubernetes-workshop/blob/master/scripts/18-setup-dynamic-creds.sh#L58). Based on your configuration, i can't found the token renewal, and you use init container. So, how you actually renew the token? or did `consul-template` that actually do it?

**Comment by sethvargo** [comment]
Consul Template renews the token
