### ISSUE TITLE
Grant the service account twice

### ISSUE THREAD

**Issue by Streppel** [sethvargo/vault-kubernetes-workshop#9]
No big deal, but on section 6 the command `gcloud kms keys add-iam-policy-binding` is repeated twice unnecessarily

**Comment by sethvargo** [comment]
Hi @Streppel 

Thanks for opening an issue. I'm not sure I understand what you mean though. Can you [link to a specific point](https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet) in the code? 

There are only two calls to `add-iam-policy-binding` in the entire repo - one on the project and one on the KMS key.

**Comment by Streppel** [comment]
@sethvargo Oh, I'm sorry! I'm looking at https://codelabs.developers.google.com/codelabs/vault-on-gke/, more specifically at https://codelabs.developers.google.com/codelabs/vault-on-gke/index.html#5.

This is what I see:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/2300328/59878942-f1e5a700-937f-11e9-8a76-185e69a11861.png">

Also, thanks for the quick reply! :)

**Comment by sethvargo** [comment]
Fixed
